version: '3'

services:
  db:
    image: mysql:5.7.18
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'shop_management'
      MYSQL_USER: 'shop_management'
      MYSQL_PASSWORD: 'shop_management'