- name: Copy artifact
  copy:
    src: "{{ webapp_artifact_dir}}/{{ webapp_artifact_name }}"
    dest: "~"
  tags:
    - copy_artifact

- name: Remove webapp container
  docker_container:
    name: "{{ webapp_container_name }}"
    state: absent

- name: Remove docker image
  docker_image:
    name: "{{ webapp_image }}"
    state: absent

- name: Load docker image
  docker_image:
    name: "{{ webapp_image }}"
    load_path: "~/{{ webapp_artifact_name }}"

- name: Deploy Web app
  docker_container:
    name: "{{ webapp_container_name }}"
    image: "{{ webapp_image }}"
    network_mode: host
    restart_policy: unless-stopped
    recreate: yes

- name: Open Web App Port
  firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    state: enabled
  notify:
    - Bounce firewalld